name: manage-azure-policy-99da5f29
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'initiatives/RobecoSql_RobecoSql/**'
#      - 'initiatives/RobecoSqlManualPolicy_e0a278cf4e124d49b67fe377/**'
#      - .github/workflows/manage-azure-policy-99da5f29.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_99da5f29}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          initiatives/RobecoSql_RobecoSql/**
          initiatives/RobecoSqlManualPolicy_e0a278cf4e124d49b67fe377/**
